// Generated by CoffeeScript 1.8.0
(function() {
  var FunctionValue, Value, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Value = require("./Value");

  _ = require("../utilities");

  module.exports = FunctionValue = (function(_super) {
    __extends(FunctionValue, _super);

    function FunctionValue(base, stops) {
      this.base = base;
      this.stops = stops;
    }

    FunctionValue.prototype.toMGLValue = function(options) {
      var stops;
      stops = _.map(this.stops, function(stop) {
        return [stop[0], Value.toMGLValue(stop[1], options)];
      });
      if (this.base) {
        return {
          base: Value.toMGLValue(this.base, options),
          stops: stops
        };
      } else {
        return {
          stops: stops
        };
      }
    };

    return FunctionValue;

  })(Value);

}).call(this);
