// Generated by CoffeeScript 1.8.0
(function() {
  var Expression, ValueMacroReferenceExpression, literal, util, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Expression = require("./Expression");

  literal = require("./LiteralExpression").literal;

  util = require('util');

  _ = require("../utilities");

  module.exports = ValueMacroReferenceExpression = (function(_super) {
    __extends(ValueMacroReferenceExpression, _super);

    function ValueMacroReferenceExpression(name, argExpressions) {
      this.name = name;
      this.argExpressions = argExpressions;
    }

    ValueMacroReferenceExpression.prototype.toValues = function(scope, options) {
      var args, macro;
      args = this.argExpressions.map(function(arg) {
        return _.extend({
          values: arg.expression.toValues(scope, options)
        }, arg);
      });
      if (macro = scope.getValueMacro(this.name, args, options)) {
        return macro.toValues(args, options);
      } else {
        throw new Error("Could not find value macro '" + this.name + "'");
      }
    };

    return ValueMacroReferenceExpression;

  })(Expression);

}).call(this);
