// Generated by CoffeeScript 1.8.0
(function() {
  var ClassScope, LayerScope, Scope, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Scope = require("./Scope");

  ClassScope = require('./ClassScope');

  _ = require('../utilities');

  module.exports = LayerScope = (function(_super) {
    __extends(LayerScope, _super);

    LayerScope.prototype.selector = null;

    LayerScope.prototype.addMetaRule = function(name, expressions) {
      if (this.metaRules[name]) {
        throw new Error("Duplicate entries for metarule '" + name + "'");
      }
      return this.metaRules[name] = expressions;
    };

    LayerScope.prototype.addClassScope = function(name) {
      var _base;
      return (_base = this.classScopes)[name] || (_base[name] = new ClassScope(this));
    };

    LayerScope.prototype.setFilter = function(filterExpression) {
      if (this.filterExpression) {
        throw new Error("Duplicate filters");
      }
      return this.filterExpression = filterExpression;
    };

    LayerScope.prototype.setSource = function(source) {
      if (this.source) {
        throw new Error("Duplicate sources");
      }
      return this.source = source;
    };

    function LayerScope(parent) {
      LayerScope.__super__.constructor.call(this, parent);
      this.classScopes = {};
      this.metaRules = {};
    }

    LayerScope.prototype.toMGLLayerScope = function(options) {
      var filterOptions, metaFilterRule, metaRules, metaSourceRule, paintClassRules, paintRules, _ref;
      options = _.extend({
        scope: "layer"
      }, options);
      if (this.filterExpression) {
        filterOptions = _.extend({
          filter: true,
          meta: true,
          rule: "filter"
        }, options);
        metaFilterRule = {
          filter: (_ref = this.filterExpression) != null ? _ref.toMGLFilter(this, filterOptions) : void 0
        };
      } else {
        metaFilterRule = null;
      }
      if (this.source) {
        if (!this.getSourceScope(this.source)) {
          throw "Unknown source '" + this.source + "'";
        }
        metaSourceRule = {
          source: this.source
        };
      } else {
        metaSourceRule = null;
      }
      metaRules = this.toMGLRules(_.extend({
        meta: true
      }, options), this.metaRules);
      paintRules = {
        paint: this.toMGLRules(options, this.rules)
      };
      paintClassRules = _.objectMap(this.classScopes, (function(_this) {
        return function(scope, name) {
          return ["paint." + name, scope.toMGLClassScope(options)];
        };
      })(this));
      return _.extend(metaRules, paintRules, paintClassRules, metaFilterRule, metaSourceRule);
    };

    return LayerScope;

  })(Scope);

}).call(this);
