// Generated by CoffeeScript 1.8.0
(function() {
  var AttributeReferenceValue, Value,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Value = require("./Value");

  module.exports = AttributeReferenceValue = (function(_super) {
    __extends(AttributeReferenceValue, _super);

    function AttributeReferenceValue(name) {
      this.name = name;
    }

    AttributeReferenceValue.prototype.toMGLValue = function(options) {
      return "{" + this.name + "}";
    };

    return AttributeReferenceValue;

  })(Value);

}).call(this);

//# sourceMappingURL=AttributeReferenceValue.js.map
