// Generated by CoffeeScript 1.8.0
(function() {
  var Value;

  module.exports = Value = (function() {
    function Value() {}

    Value.toMGLValue = function(value, options) {
      if (value.toMGLValue) {
        return value.toMGLValue(options);
      } else {
        return value;
      }
    };

    Value.prototype.toMGLValue = function(options) {
      throw "Abstract method";
    };

    return Value;

  })();

}).call(this);

//# sourceMappingURL=Value.js.map
