// Generated by CoffeeScript 1.8.0
(function() {
  var AttributeReferenceValue, ComparisonOperatorExpression, Expression, assert, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Expression = require("./Expression");

  AttributeReferenceValue = require("../values/AttributeReferenceValue");

  _ = require("../utilities");

  assert = require("assert");

  module.exports = ComparisonOperatorExpression = (function(_super) {
    __extends(ComparisonOperatorExpression, _super);

    function ComparisonOperatorExpression(left, operator, right) {
      this.left = left;
      this.operator = operator;
      this.right = right;
    }

    ComparisonOperatorExpression.prototype.toMGLFilter = function(scope, options) {
      var lvalue, rvalue;
      lvalue = this.left.toValue(scope, options);
      rvalue = this.right.toValue(scope, options);
      assert(lvalue instanceof AttributeReferenceValue);
      assert(!(rvalue instanceof AttributeReferenceValue));
      return [this.operator, lvalue.toMGLValue(options), rvalue.toMGLValue(options)];
    };

    return ComparisonOperatorExpression;

  })(Expression);

}).call(this);
