// Generated by CoffeeScript 1.8.0
(function() {
  if (module.exports) {
    module.exports = require("./parser");
  } else if (window) {
    window.ScreeSS = require("./parser");
  }

}).call(this);

//# sourceMappingURL=main.js.map
