// Generated by CoffeeScript 1.8.0
(function() {
  var ArrayValue, Value, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Value = require("./Value");

  _ = require("../utilities");

  module.exports = ArrayValue = (function(_super) {
    __extends(ArrayValue, _super);

    function ArrayValue(expressions) {
      this.expressions = expressions;
    }

    ArrayValue.prototype.toMGLValue = function(scope, options) {
      return _.map(this.expressions, function(expression) {
        return expression.toMGLValue(scope, options);
      });
    };

    return ArrayValue;

  })(Value);

}).call(this);
