// Generated by CoffeeScript 1.8.0
(function() {
  var CLI, Package;

  Package = require('../package.json');

  CLI = require('commander');

  CLI.version(Package.version);

  CLI.option('-p, --peppers', 'Add peppers');

  CLI.parse(process.argv);

}).call(this);
