// Generated by CoffeeScript 1.8.0
(function() {
  var ColorValue, FunctionValue, LiteralValue, Value, assert, _;

  ColorValue = require("./values/ColorValue");

  LiteralValue = require("./values/LiteralValue");

  FunctionValue = require("./values/FunctionValue");

  _ = require("./utilities");

  assert = require("assert");

  Value = require('./values/Value');

  module.exports = {
    valueMacros: {
      source: function(source, options) {
        debugger;
        var name;
        name = Value.toMGLValue(source.name != null, options) || _.uniq();
        delete source.name;
        if (source["tile-size"]) {
          source.tileSize = source["tile-size"];
          delete source["tile-size"];
        }
        options.getGlobalScope().addSource(name, source);
        return [new LiteralValue(name)];
      },
      identity: function(args) {
        return _.values(args);
      },
      hsv: function(args) {
        return [ColorValue.hsla(args['0'], args['1'], args['2'], 1)];
      },
      hsva: function(args) {
        return [ColorValue.hsla(args['0'], args['1'], args['2'], args['3'])];
      },
      hsl: function(args) {
        return [ColorValue.hsla(args['0'], args['1'], args['2'], 1)];
      },
      hsla: function(args) {
        return [ColorValue.hsla(args['0'], args['1'], args['2'], args['3'])];
      },
      rgb: function(args) {
        return [ColorValue.rgba(args['0'], args['1'], args['2'], 1)];
      },
      rgba: function(args) {
        return [ColorValue.rgba(args['0'], args['1'], args['2'], args['3'])];
      },
      polygon: function() {
        return [new LiteralValue("Polygon")];
      },
      point: function() {
        return [new LiteralValue("Point")];
      },
      line: function(args, options) {
        if (options.property === "type" && options.isMetaProperty) {
          return new LiteralValue("LineString");
        } else if (options.isFilter()) {
          return new LiteralValue("line");
        } else {
          throw new Error("The use of 'line' is ambigious in this context");
        }
      },
      'function': function(args) {
        var key, stop, stops, value;
        stops = [];
        for (key in args) {
          value = args[key];
          if (key === "base") {
            continue;
          }
          if ((stop = parseInt(key)) !== NaN) {
            stops.push([key, value]);
          } else {
            assert(false);
          }
        }
        assert(stops.length > 0);
        return [new FunctionValue(args.base, stops)];
      }
    }
  };

}).call(this);
