// Generated by CoffeeScript 1.8.0
(function() {
  var Options;

  module.exports = Options = (function() {
    Options.prototype.getGlobalScope = function() {
      return this.scopeStack[0];
    };

    Options.prototype.getScope = function() {
      return this.scopeStack[this.scopeStack.length - 1];
    };

    Options.prototype.pushFilter = function() {
      return this.filters++;
    };

    Options.prototype.popFilter = function() {
      return --this.filters;
    };

    Options.prototype.isFilter = function() {
      return this.filters > 0;
    };

    function Options() {
      this.valueMacroStack = [];
      this.ruleMacroStack = [];
      this.scopeStack = [];
      this.filters = 0;
      this.rule = null;
      this.isMetaRule = false;
    }

    return Options;

  })();

}).call(this);
