// Generated by CoffeeScript 1.8.0
(function() {
  var GlobalScope, Globals, LayerScope, Options, RuleMacro, Scope, ValueMacro, assert, literalValue, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Scope = require("./Scope");

  _ = require("../utilities");

  LayerScope = require('./LayerScope');

  Globals = require('../globals');

  ValueMacro = require('../macros/ValueMacro');

  RuleMacro = require('../macros/RuleMacro');

  assert = require('assert');

  Options = require('../Options');

  literalValue = require('../values/LiteralValue').literalValue;

  module.exports = GlobalScope = (function(_super) {
    __extends(GlobalScope, _super);

    function GlobalScope() {
      var fn, name, _ref, _ref1;
      GlobalScope.__super__.constructor.call(this);
      this.layerScopes = {};
      this.sources = {};
      _ref = Globals.valueMacros;
      for (name in _ref) {
        fn = _ref[name];
        this.addValueMacro(name, null, fn);
      }
      _ref1 = Globals.ruleMacros;
      for (name in _ref1) {
        fn = _ref1[name];
        this.addRuleMacro(name, null, fn);
      }
    }

    GlobalScope.prototype.addSource = function(name, source) {
      return this.sources[name] = source;
    };

    GlobalScope.prototype.getGlobalScope = function() {
      return this;
    };

    GlobalScope.prototype.getValueMacro = function(name, argValues) {
      var macro;
      if (macro = GlobalScope.__super__.getValueMacro.apply(this, arguments)) {
        return macro;
      } else if (argValues.length === 0) {
        return ValueMacro.createFromValue(name, this, literalValue(name));
      } else {
        return null;
      }
    };

    GlobalScope.prototype.addLayerScope = function(name, scope) {
      if (this.layerScopes[name]) {
        throw new Error("Duplicate entries for layer scope '" + name + "'");
      }
      return this.layerScopes[name] = new LayerScope(name, this);
    };

    GlobalScope.prototype.toMGLGlobalScope = function(options) {
      var layers, rules, sources, transition;
      if (options == null) {
        options = new Options();
      }
      options.scopeStack.push(this);
      layers = _.map(this.layerScopes, function(layer) {
        return layer.toMGLLayerScope(options);
      });
      rules = this.toMGLRules(options, this.rules);
      sources = _.objectMapValues(this.sources, function(name, source) {
        return _.objectMapValues(source, function(key, value) {
          return value.toMGLValue(options);
        });
      });
      transition = {
        duration: rules["transition-delay"],
        delay: rules["transition-duration"]
      };
      delete rules["transition-delay"];
      delete rules["transition-duration"];
      options.scopeStack.pop();
      return _.extend(rules, {
        version: 6,
        layers: layers,
        sources: sources,
        transition: transition
      });
    };

    return GlobalScope;

  })(Scope);

}).call(this);
